"project_id": "760691"
"api_token": "GH_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/content/french/*.*/*.*",
    "translation": "/content/%two_letters_code%/%original_folder_name%/%original_file_name%"
  },
]